/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package tv.harukaze.ti.nend.android;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;

import org.appcelerator.titanium.util.Log;
import org.appcelerator.titanium.util.TiConfig;

@Kroll.module(name="Tinend4android", id="tv.harukaze.ti.nend.android")
public class Tinend4androidModule extends KrollModule
{

	// Standard Debugging variables
	public static int Spotid;
	public static String Apikey;

	// You can define constants with @Kroll.constant, for example:
	// @Kroll.constant public static final String EXTERNAL_NAME = value;
	
	public Tinend4androidModule() {
		super();
	}

	// Methods
	@Kroll.method
	public void setSpotid(int spotid){
		Spotid = spotid;
	}
	// Methods
	@Kroll.method
	public void setApikey(String apikey){
		Apikey = apikey;
	}
}
